# Generated by Django 4.0.3 on 2022-10-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_url_table_delete_longtoshort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_table',
            old_name='visited_count',
            new_name='visit_count',
        ),
    ]
